name: vig2ipynb
on:
  push:
    paths:
    - 'vignettes/**.Rmd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/vig2ipynb_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Python dependencies
        run: |
          python -m pip install -r vig2ipynb_requirements.txt
          
      - name: Execute Bash code to generate notebooks
        run: bash vig2ipynb.sh
      
      - name: Commit and push new notebooks
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git status
          git add vignettes/*.ipynb
          timestamp=$(date -u)
          git commit -m "Latest notebook update: ${timestamp}" || exit 0
          git push
          
      - name: Execute Bash code to test notebooks
        run: bash vig2ipynb_test.sh
